[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["lmomoh <Lmomoh@eprod.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
black = "^24.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
